<?php

/**
 * @file
 * Contains upload_details.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function upload_details_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the upload_details module.
    case 'help.page.upload_details':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module for uploading details of students in bulk') . '</p>';
      return $output;

    default:
  }
}
